curl "https://calendly.com/api/booking/event_types/EBAXZXNO5XL6LLRJ/calendar/range?timezone=America%2FNew_York&diagnostics=false&range_start=$(date +%Y-%m-%d)&range_end=2021-04-14" \
  -H 'authority: calendly.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: "Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'x-newrelic-id: VwUDWFRaGwECU1dbDgY=' \
  -H 'x-csrf-token: m/5PtZwt0zgo/sS71kRSp1itt37MaEamzZhMvoMAl3Lmu1SA7Q5LRpC8bHG2zcdrOXwQcU7qFOajWKapxzduDQ==' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://calendly.com/eric-s-covid-vaccine/covid-vaccine?month=2021-02' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'dnt: 1' \
  -H 'sec-gpc: 1' \
  --compressed
